# Site settings
title: DataHack
email: contact@datahack-il.com
baseurl: ''
description: "A website for the DataHack hackathon, Nov 2015."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#f3f8ff'
  links: '#00b0b7'

# Footer settings
footer: DataHack

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
